# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1696, 833)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 1281, 721))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 770, 1101, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_x = QtWidgets.QLabel(self.frame)
        self.label_x.setGeometry(QtCore.QRect(10, 10, 71, 41))
        self.label_x.setObjectName("label_x")
        self.label_y = QtWidgets.QLabel(self.frame)
        self.label_y.setGeometry(QtCore.QRect(180, 10, 71, 41))
        self.label_y.setObjectName("label_y")
        self.label_X = QtWidgets.QLabel(self.frame)
        self.label_X.setGeometry(QtCore.QRect(80, 10, 91, 41))
        self.label_X.setText("")
        self.label_X.setObjectName("label_X")
        self.label_Y = QtWidgets.QLabel(self.frame)
        self.label_Y.setGeometry(QtCore.QRect(270, 10, 101, 41))
        self.label_Y.setText("")
        self.label_Y.setObjectName("label_Y")
        self.label_D = QtWidgets.QLabel(self.frame)
        self.label_D.setGeometry(QtCore.QRect(410, 10, 101, 41))
        self.label_D.setObjectName("label_D")
        self.label_d = QtWidgets.QLabel(self.frame)
        self.label_d.setGeometry(QtCore.QRect(520, 10, 121, 41))
        self.label_d.setText("")
        self.label_d.setObjectName("label_d")
        self.btn_save = QtWidgets.QPushButton(self.frame)
        self.btn_save.setGeometry(QtCore.QRect(610, 0, 171, 61))
        self.btn_save.setObjectName("btn_save")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 0, 171, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(1340, 10, 261, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Z_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Z_label.setObjectName("Z_label")
        self.gridLayout_2.addWidget(self.Z_label, 2, 1, 1, 1)
        self.X_output = QtWidgets.QLabel(self.gridLayoutWidget)
        self.X_output.setObjectName("X_output")
        self.gridLayout_2.addWidget(self.X_output, 0, 2, 1, 1)
        self.X_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.X_edit.setObjectName("X_edit")
        self.gridLayout_2.addWidget(self.X_edit, 0, 3, 1, 1)
        self.Y_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Y_label.setObjectName("Y_label")
        self.gridLayout_2.addWidget(self.Y_label, 1, 1, 1, 1)
        self.Y_output = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Y_output.setObjectName("Y_output")
        self.gridLayout_2.addWidget(self.Y_output, 1, 2, 1, 1)
        self.Y_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Y_edit.setObjectName("Y_edit")
        self.gridLayout_2.addWidget(self.Y_edit, 1, 3, 1, 1)
        self.Z_output = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Z_output.setObjectName("Z_output")
        self.gridLayout_2.addWidget(self.Z_output, 2, 2, 1, 1)
        self.Z_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Z_edit.setObjectName("Z_edit")
        self.gridLayout_2.addWidget(self.Z_edit, 2, 3, 1, 1)
        self.X_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.X_label.setObjectName("X_label")
        self.gridLayout_2.addWidget(self.X_label, 0, 1, 1, 1)
        self.R_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.R_edit.setObjectName("R_edit")
        self.gridLayout_2.addWidget(self.R_edit, 3, 3, 1, 1)
        self.R_output = QtWidgets.QLabel(self.gridLayoutWidget)
        self.R_output.setObjectName("R_output")
        self.gridLayout_2.addWidget(self.R_output, 3, 2, 1, 1)
        self.R_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.R_label.setObjectName("R_label")
        self.gridLayout_2.addWidget(self.R_label, 3, 1, 1, 1)
        self.btn_go = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_go.setObjectName("btn_go")
        self.gridLayout_2.addWidget(self.btn_go, 4, 3, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(1340, 560, 261, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_suck = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_suck.setObjectName("btn_suck")
        self.horizontalLayout_4.addWidget(self.btn_suck)
        self.btn_free = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_free.setObjectName("btn_free")
        self.horizontalLayout_4.addWidget(self.btn_free)
        self.btn_close = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_4.addWidget(self.btn_close)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(1340, 260, 261, 281))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_z_reduce = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_z_reduce.setObjectName("btn_z_reduce")
        self.gridLayout_3.addWidget(self.btn_z_reduce, 3, 1, 1, 1)
        self.btn_z_increase = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_z_increase.setObjectName("btn_z_increase")
        self.gridLayout_3.addWidget(self.btn_z_increase, 3, 0, 1, 1)
        self.btn_x_reduce = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_x_reduce.setObjectName("btn_x_reduce")
        self.gridLayout_3.addWidget(self.btn_x_reduce, 1, 1, 1, 1)
        self.btn_y_reduce = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_y_reduce.setObjectName("btn_y_reduce")
        self.gridLayout_3.addWidget(self.btn_y_reduce, 2, 1, 1, 1)
        self.btn_y_increase = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_y_increase.setObjectName("btn_y_increase")
        self.gridLayout_3.addWidget(self.btn_y_increase, 2, 0, 1, 1)
        self.btn_x_increase = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_x_increase.setObjectName("btn_x_increase")
        self.gridLayout_3.addWidget(self.btn_x_increase, 1, 0, 1, 1)
        self.input_interval = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.input_interval.setText("")
        self.input_interval.setObjectName("input_interval")
        self.gridLayout_3.addWidget(self.input_interval, 0, 0, 1, 1)
        self.btn_set = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_set.setObjectName("btn_set")
        self.gridLayout_3.addWidget(self.btn_set, 0, 1, 1, 1)
        self.btn_back = QtWidgets.QPushButton(Form)
        self.btn_back.setGeometry(QtCore.QRect(1340, 640, 113, 32))
        self.btn_back.setObjectName("btn_back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_x.setText(_translate("Form", "X"))
        self.label_y.setText(_translate("Form", "Y"))
        self.label_D.setText(_translate("Form", "D"))
        self.btn_save.setText(_translate("Form", "Save Img"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.Z_label.setText(_translate("Form", "Z"))
        self.X_output.setText(_translate("Form", "0                                   "))
        self.Y_label.setText(_translate("Form", "Y"))
        self.Y_output.setText(_translate("Form", "0"))
        self.Z_output.setText(_translate("Form", "0"))
        self.X_label.setText(_translate("Form", "X      "))
        self.R_output.setText(_translate("Form", "0"))
        self.R_label.setText(_translate("Form", "R"))
        self.btn_go.setText(_translate("Form", "Go"))
        self.btn_suck.setText(_translate("Form", "suck"))
        self.btn_free.setText(_translate("Form", "free"))
        self.btn_close.setText(_translate("Form", "close"))
        self.btn_z_reduce.setText(_translate("Form", "Z-"))
        self.btn_z_increase.setText(_translate("Form", "Z+"))
        self.btn_x_reduce.setText(_translate("Form", "X-"))
        self.btn_y_reduce.setText(_translate("Form", "Y-"))
        self.btn_y_increase.setText(_translate("Form", "Y+"))
        self.btn_x_increase.setText(_translate("Form", "X+"))
        self.btn_set.setText(_translate("Form", "        Set      "))
        self.btn_back.setText(_translate("Form", "Back to O"))
